"""Shared system-prompt snippet for infra agents that may produce architecture diagrams."""

INFRA_D2_MANIFEST_SHAPE_MAPPING = (
    "Use the following D2 node shapes for each infrastructure manifest type:\n"
    "- ConfigMap: document\n"
    "- PersistentVolumeClaim (PVC): cylinder\n"
    "- Secret: document\n"
    "- Pod: oval\n"
    "- VirtualMachine / VM instance: rectangle\n"
    "- Deployment: page\n"
    "- StatefulSet: page\n"
    "- DaemonSet: page\n"
    "- ServiceAccount: person\n"
    "- Ingress / Route: circle\n"
    "- Service: rectangle\n"
    "- Datastore: cylinder\n"
    "- Datacenter: cloud\n"
    "- Network: hexagon\n"
    "- Namespace: cloud"
)

INFRA_D2_NODE_LABEL_RULE = (
    "Label every node with both the resource name and its manifest type "
    "(for example: `nginx-service (Service)` or `ollama-webui (Namespace)`)."
)

INFRA_D2_ANALYSIS_GUIDELINES = (
    "When analyzing infrastructure and creating diagrams, follow these guidelines:\n"
    "1. Include Namespace and ResourceQuota in the analysis.\n"
    "2. For Secret, ConfigMap, ServiceAccount, and PVC: determine which Pod references each "
    "resource and show that relationship in the diagram when referenced.\n"
    "3. For PVC: identify the mount path used by the Pod and display it in the diagram.\n"
    "4. For Ingress / Route: confirm the service domain and whether traffic is secure "
    "(HTTPS/HTTP) and display both in the diagram.\n"
    "5. For Service: confirm port information and display it in the diagram.\n"
    "6. For Deployment and StatefulSet: display replica count.\n"
    "7. For DaemonSet: display nodeSelector."
)

INFRA_ARCHITECTURE_D2_INSTRUCTION = (
    "When the user requests an architecture diagram, structure diagram, topology, or visualization "
    "(including requests routed from archi-analysis), query the relevant infrastructure resources first, "
    "then provide a brief explanation in Korean and MUST include a fenced ```d2 code block with a "
    "complete D2 diagram that uses real resource names and relationships from the query results.\n\n"
    f"{INFRA_D2_MANIFEST_SHAPE_MAPPING}\n\n"
    f"{INFRA_D2_NODE_LABEL_RULE}\n\n"
    f"{INFRA_D2_ANALYSIS_GUIDELINES}\n\n"
    "Apply shapes with D2 node blocks, for example:\n"
    "```d2\n"
    "direction: down\n"
    "\n"
    "ingress: my-ingress (Ingress) {\n"
    "  shape: circle\n"
    "}\n"
    "service: my-service (Service) {\n"
    "  shape: rectangle\n"
    "}\n"
    "pod: my-pod (Pod) {\n"
    "  shape: oval\n"
    "}\n"
    "\n"
    "ingress -> service -> pod\n"
    "```\n"
    "Never say that you cannot generate diagrams."
)
